site :opscode

cookbook 'apt'
cookbook 'yum',  git: 'git://github.com/opscode-cookbooks/yum.git', tag: 'v2.4.4'  # 2.xの最新
cookbook 'mysql'
cookbook 'database'
cookbook 'timezone'
cookbook 'timezone-ii'
